### ISSUE TITLE
1.20.2 to 1.20.4, now can't open bags

### ISSUE THREAD

**Issue by 8JJEETTii6** [Valorless/HavenBags#5]
Hello,

Preemptively, want to thank you for the absolutely amazing mod. It is far and away the best bag/backpack mod I've used!

Having recently updated my server to 1.20.4 and also Havenbags to 1.6.4.478, no one can open their bags. They still appear in game, and the description still has the content listed but they are not useable.

<img width="827" alt="Screenshot 2024-01-11 213332" src="https://github.com/Valorless/HavenBags/assets/156363396/c884a683-e0be-4459-9957-0ee6ce902a1e">

server console reports:

[11.01 21:25:54] [Server] [WARN] [HavenBags] Multiple instances of the same bag is opened by: jjeettii & jjeettii
[11.01 21:25:54] [Server] [WARN] [HavenBags] They might be trying to dupe items. Forcing their bags to close.
[11.01 21:25:54] [Server] [ERROR] Could not pass event PlayerInteractEvent to HavenBags v1.6.4.478
[11.01 21:25:54] [Server] java.lang.NoClassDefFoundErrorde/jeff_media/chestsort/api/ChestSortAPI
[11.01 21:25:54] [Server] 	at valorless.havenbags.BagGUI.<init>(BagGUI.java:94) ~[HavenBags-1.6.4.478-SNAPSHOT.jar:?]
[11.01 21:25:54] [Server] 	at valorless.havenbags.BagListener.onPlayerInteract(BagListener.java:171) ~[HavenBags-1.6.4.478-SNAPSHOT.jar:?]
[11.01 21:25:54] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor267.execute(Unknown Source) ~[?:?]
[11.01 21:25:54] [Server] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[11.01 21:25:54] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[11.01 21:25:54] [Server] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
[11.01 21:25:54] [Server] 	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:592) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
[11.01 21:25:54] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1939) ~[?:?]
[11.01 21:25:54] [Server] 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
[11.01 21:25:54] [Server] 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
[11.01 21:25:54] [Server] 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
[11.01 21:25:54] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[11.01 21:25:54] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[11.01 21:25:54] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[11.01 21:25:54] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
[11.01 21:25:54] [Server] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-382]
[11.01 21:25:54] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11.01 21:25:54] [Server] Caused byjava.lang.ClassNotFoundException: de.jeff_media.chestsort.api.ChestSortAPI
[11.01 21:25:54] [Server] 	... more

**Comment by 8JJEETTii6** [comment]
Addendum,

I just updated chestsort to 13.6.6 and bags do work again. However, all contents have disappeared. I can roll back to a backup pre 1.20.4 update, but is there some way to update without this problem occuring?

thanks

**Comment by Valorless** [comment]
Greetings!
From the console error I can see there's an issue fetching ChestSort, which by my negligence causes the rest of the function to not run. (The bag content is loaded afterwards)
Which causes the error shown in the console.
 _(I'll wrap this section inside a try/catch to prevent this issue in the future.)_

In regards to the bags being empty suddenly.
Could you try holding one of the broken bags, do '/bags info', and locate if the bag file is on the server.
_(Should be in /plugins/HavenBags/Bags/\<owner>/\<bag-uuid>.json)_

When attempting to open an empty bag, is there anything out of the usual in the console?

**Comment by Valorless** [comment]
For good measure, you should try and restart the server to clear the plugin's cache :)

**Comment by 8JJEETTii6** [comment]
Hi!

I was just going through the update from backup to 1.20.4 and both haven and sort again as I received your messages. I made sure to update both sort and bags before starting the server after the update and it seems to have fixed the problem.

I'm not all that experienced at server admin (first server I've ever set up) so I may have made some error along the way the first time round that messed up the mod/s somehow. In any case, all is fixed. Thank you so so much for your super fast reply and help!

I'm dropping you a dono on Ko-fi :)

**Comment by Valorless** [comment]
I'm glad the issue is resolved, and very pleased that you like the plugin ^^
Thank you so much for the donation :)

If you have any other issues, questions or suggestions, feel free to reach out again :D

I've done some minor changes to how the bag is loaded, mainly some fail saves; And a command to view the raw metadata of the item.
I'll take another look around, to see what I could optimize before posting the update.
